- name: import needed variables
  include_vars: b2_auth.yml

- name: ensure b2 installed
  pip:
    name: b2
    state: latest

- name: auth params for b2
  command: /usr//bin/b2 "{{ accountId }}" "{{ applicationKey }}

